import * as THREE from 'three';
const mat=(color,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness:.72,metalness});
function mesh(g,m,p,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o;}
export function coastRadius(a){return (21+52*Math.pow(Math.max(0,-Math.sin(a)),3))*(1+.11*Math.sin(a*3+.8)+.07*Math.cos(a*5-.6)+.035*Math.sin(a*7));}
export function terrain(sand,grass,rock){const group=new THREE.Group();group.name='asymmetric-island';
 for(const [material,height,scale,depth] of [[sand,1.08,1,-.9],[grass,1.35,.91,1.05]]){const points=[],indices=[],n=128;points.push(0,height,0);for(let i=0;i<n;i++){const a=i/n*Math.PI*2,r=coastRadius(a)*scale;points.push(Math.cos(a)*r,height,Math.sin(a)*r);}for(let i=0;i<n;i++)indices.push(0,1+(i+1)%n,1+i);for(let i=0;i<n;i++){const a=i/n*Math.PI*2,r=coastRadius(a)*(scale+.025);points.push(Math.cos(a)*r,depth,Math.sin(a)*r);}for(let i=0;i<n;i++){const j=(i+1)%n;indices.push(i+1,j+1,n+i+1,j+1,n+j+1,n+i+1);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(points,3));geo.setIndex(indices);geo.computeVertexNormals();mesh(geo,material,group);}
 for(let i=0;i<48;i++){const a=i*2.399,r=coastRadius(a)*(.93+(i%3)*.025);const b=mesh(new THREE.IcosahedronGeometry(.7+(i%5)*.2,1),rock,group,Math.cos(a)*r,.7,Math.sin(a)*r);b.scale.set(1.4,.7+(i%3)*.3,1);b.rotation.set(i*.2,i*.7,.1);}
 // A taller, irregular headland encloses the hidden room without obscuring its entrance.
 for(let i=0;i<36;i++){const x=(i%7-3)*1.65,z=-10-Math.floor(i/7)*1.1;const b=mesh(new THREE.IcosahedronGeometry(1.6+(i%3)*.3,1),rock,group,x,3.6+(i%5)*.75,z);b.scale.set(1.2,1.5,1);b.rotation.set(i*.11,i*.4,i*.08);}
 return group;
}
export function sailingShip(){const ship=new THREE.Group();ship.name='pofidik-sailing-ship';const wood=mat('#754b30'),trim=mat('#d7aa58'),deck=mat('#cba16c'),brass=mat('#d7b45a',.65);
 wood.side=THREE.DoubleSide;
 // A pointed bow, flared timber sides and deep keel replace the oval raft.
 const sections=[[-6.2,1.15],[-5.8,1.7],[-3.5,2.25],[0,2.5],[3.5,2.1],[5,1.45],[6.1,.65],[7.1,0]],points=[],indices=[];
 for(const [z,w]of sections)for(const [factor,y]of [[0,-1.3],[.67,-.65],[1,.65],[.92,1]])points.push(w*factor,y,z);
 for(let side=0;side<2;side++){const positions=points.map((v,i)=>i%3===0?v*(side?1:-1):v);const ix=[];for(let i=0;i<sections.length-1;i++)for(let j=0;j<3;j++){const k=i*4+j;ix.push(k,k+4,k+1,k+1,k+4,k+5);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setIndex(side?ix:ix.reverse());geo.computeVertexNormals();mesh(geo,wood,ship);}
 const stern=new THREE.BufferGeometry();stern.setAttribute('position',new THREE.Float32BufferAttribute([-1.058,1,-6.2,-1.15,.65,-6.2,-.77,-.65,-6.2,0,-1.3,-6.2,.77,-.65,-6.2,1.15,.65,-6.2,1.058,1,-6.2],3));stern.setIndex([0,1,3,1,2,3,0,3,6,3,4,5,3,5,6]);stern.computeVertexNormals();mesh(stern,wood,ship);mesh(new THREE.BoxGeometry(2.2,.14,.13),trim,ship,0,1.05,-6.21);
 const outline=new THREE.Shape();sections.forEach(([z,w],i)=>i?outline.lineTo(-w*.92,z):outline.moveTo(-w*.92,z));[...sections].reverse().forEach(([z,w])=>outline.lineTo(w*.92,z));outline.closePath();const floor=mesh(new THREE.ShapeGeometry(outline),deck,ship,0,1,0);floor.rotation.x=Math.PI/2;floor.material.side=THREE.DoubleSide;
 for(let side of [-1,1]){for(let i=1;i<sections.length;i++){const [z,w]=sections[i];mesh(new THREE.CylinderGeometry(.055,.055,.85,8),trim,ship,side*w*.93,1.4,z);if(i>1){const [pz,pw]=sections[i-1],a=new THREE.Vector3(side*pw*.93,1.82,pz),b=new THREE.Vector3(side*w*.93,1.82,z),d=b.clone().sub(a);const rail=mesh(new THREE.CylinderGeometry(.075,.075,d.length(),8),trim,ship,...a.clone().add(b).multiplyScalar(.5).toArray());rail.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());}}}
 for(let i=0;i<14;i++)mesh(new THREE.BoxGeometry(.025,.012,8.1),wood,ship,-1.7+i*.26,1.012,.2);
 const cabin=mesh(new THREE.BoxGeometry(2.7,1.8,2.2),wood,ship,0,1.9,-3.2);mesh(new THREE.BoxGeometry(3.1,.18,2.6),trim,ship,0,2.9,-3.2);for(let x of [-.85,.85]){mesh(new THREE.TorusGeometry(.27,.055,8,24),brass,ship,x,2,-2.07);mesh(new THREE.CircleGeometry(.23,24),mat('#496878'),ship,x,2,-2.065);}
 for(const z of [-1.4,2.2]){mesh(new THREE.CylinderGeometry(.10,.15,7.5,12),wood,ship,0,4.6,z);const spar=mesh(new THREE.CylinderGeometry(.075,.075,4.5,8),trim,ship,0,7.9,z);spar.rotation.z=Math.PI/2;const g=new THREE.PlaneGeometry(4.1,3.1,16,12),a=g.attributes.position;for(let i=0;i<a.count;i++)a.setZ(i,Math.sin((a.getX(i)/4.1+.5)*Math.PI)*.55);g.computeVertexNormals();const sail=mesh(g,new THREE.MeshStandardMaterial({color:'#fff2cc',roughness:.9,side:THREE.DoubleSide}),ship,0,6.3,z);sail.name='wind-sail';sail.userData.rest=Float32Array.from(g.attributes.position.array);const rope=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-2,1,z),new THREE.Vector3(0,8,z),new THREE.Vector3(2,1,z)]),new THREE.LineBasicMaterial({color:'#94785b'}));ship.add(rope);}
 const bowsprit=mesh(new THREE.CylinderGeometry(.09,.11,3,10),wood,ship,0,1.6,7.2);bowsprit.rotation.x=Math.PI/2;
 mesh(new THREE.BoxGeometry(.9,.08,1.3),deck,ship,-1.1,1.95,3.5);return ship;
}

export function forest(scene,wind){const grove=new THREE.Group();grove.name='deep-island-forest';scene.add(grove);const bark=mat('#72563c'),leaves=[mat('#367d4f'),mat('#488e57'),mat('#5a9c60')];
 for(let i=0;i<46;i++){const row=Math.floor(i/9),x=(i%9-4)*8+Math.sin(i*3)*2,z=-22-row*10;const g=new THREE.Group();g.position.set(x,1.35,z);grove.add(g);const height=6+(i%4)*1.1;mesh(new THREE.CylinderGeometry(.24,.5,height,8),bark,g,0,height/2,0);for(let j=0;j<3;j++){const crown=mesh(new THREE.IcosahedronGeometry(2.1+(i%3)*.25,2),leaves[(i+j)%3],g,Math.cos(j*2)*1.2,height+Math.sin(j)*.6,Math.sin(j*2)*1.2);crown.scale.set(1.18,.85+(j%2)*.2,.94);}wind.push({node:g,base:0,offset:i*.7});}
 // A continuous, low relief terrain replaces separate green domes.
 const earth=mat('#6b8955'),geo=new THREE.PlaneGeometry(94,62,48,32);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);const edge=Math.max(0,1-Math.abs(x)/47)*Math.max(0,1-Math.abs(z)/31);pos.setY(i,.12+edge*(.9+Math.sin(x*.13+z*.09)*.55+Math.cos(z*.19)*.35));}const keep=[];for(let i=0;i<geo.index.count;i+=3){const ids=[geo.index.getX(i),geo.index.getX(i+1),geo.index.getX(i+2)];if(ids.every(id=>{const x=pos.getX(id),z=pos.getZ(id)-44;return Math.hypot(x,z)<coastRadius(Math.atan2(z,x))*.89;}))keep.push(...ids);}geo.setIndex(keep);geo.computeVertexNormals();mesh(geo,earth,grove,0,1.35,-44);
 for(let i=0;i<32;i++){const a=i*2.399,r=8+(i%7)*1.25,x=Math.cos(a)*r,z=Math.sin(a)*r;if(z<0&&Math.abs(x)<5)continue;const shrub=mesh(new THREE.IcosahedronGeometry(.55,2),leaves[i%3],grove,x,1.65,z);shrub.scale.set(1.5,.6,1);for(let j=0;j<3;j++){const flower=new THREE.Group();flower.position.set(x+(j-1)*.24,1.36,z+.5);grove.add(flower);mesh(new THREE.CylinderGeometry(.018,.024,.45,5),leaves[0],flower,0,.22,0);for(let k=0;k<5;k++){const petal=mesh(new THREE.SphereGeometry(.10,7,5),mat(['#f3b7a6','#ead49a','#c4b3db'][i%3]),flower,Math.cos(k*1.257)*.1,.45,Math.sin(k*1.257)*.1);petal.scale.y=.42;}mesh(new THREE.SphereGeometry(.055,7,5),mat('#e5b644'),flower,0,.46,0);wind.push({node:flower,base:0,offset:i+j});}}
 return grove;}
